### PR TITLE
fix: warning for duplicate action name

### LINKED ISSUE #1895: [BUG] Error 500 Occurs When Adding Code Action with Duplicate Identifier
### Issue Summary

When attempting to add a code action with an identifier that is already assigned to another action, the server returns a 500 error. The accompanying error message is uninformative and does not provide meaningful guidance. This issue needs to be addressed more gracefully to enhance user experience.

Note: I apologize for the numerous bug reports; my intention is solely to contribute to the improvement of the product :)

### Steps to Reproduce

1. create a code action with identifier "aaa"
2. try to create a second code action with identifier "aaa"
3. see error

image

### Expected behavior

Upon attempting to add a code action with a duplicate identifier, Formbricks should handle the situation gracefully by providing a clear and informative error message. Instead of a server error, the user should receive a prompt indicating that the identifier is already in use, along with guidance on how to resolve the naming conflict (e.g. "The identifier 'your_identifier' is already in use for another code action. Please choose a unique identifier for the new action to avoid conflicts.").

### Other information

*No response*

### Screenshots

*No response*

### Environment

- [X] Formbricks Cloud ([app.formbricks.com](http://app.formbricks.com))
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```
- OS:
- Node:
- npm:
```

<sub>From [SyncLinear.com](https://synclinear.com) | [FOR-1682](https://linear.app/formbricks/issue/FOR-1682/[bug]-error-500-occurs-when-adding-code-action-with-duplicate)</sub>

### PR DESCRIPTION
**Pull request by Dhruwang**
## What does this PR do?

Shows a toast when someone try to create an action with a duplicate name

Fixes #1895 

Screenshot 2024-01-12 at 5 12 05 PM

## How should this be tested?

Create an action with a name that already exist for some other action

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] First PR at Formbricks? [Please sign the CLA!](https://formbricks.com/clmyhzfrymr4ko00hycsg1tvx) Without it we wont be able to merge it 🙏

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [x] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

File: apps/web/app/(app)/environments/[environmentId]/(actionsAndAttributes)/actions/components/ActionClassesTable.tsx [hunk 1]
```diff
@@ -84,6 +84,7 @@ export default function ActionClassesTable({
       <AddNoCodeActionModal
         environmentId={environmentId}
         open={isAddActionModalOpen}
+        actionClassArray={actionClasses}
```
Comment (mattinannt) [inline apps/web/app/(app)/environments/[environmentId]/(actionsAndAttributes)/actions/components/ActionClassesTable.tsx:87]: please rename to `actionClasses` ;-)

**Review by mattinannt — CHANGES_REQUESTED** [review]
@Dhruwang looks great; thank you :-) Only one small thing naming thing. When something is named with `...Array`, `data`, `...String`, .. this often is very generic and unnecessary information. So I would like to name it more like what the variable stands for, not what it is on the programming side.
