### PR TITLE
fix: ee license check

### LINKED ISSUE #2609: [BUG] Error while checking license
### Issue Summary

After a certain period of time after boot on my self-hosted instance, I see the error "Error: Error while checking license" popping up. This results in all forms being unusable, see screenshot:

Scherm­afbeelding 2024-05-13 om 10 22 08

### Steps to Reproduce

1. Self-host instance (with enterprise license I think)
2. Wait some hours

### Expected behavior

License should work

### Other information

_No response_

### Screenshots

Scherm­afbeelding 2024-05-13 om 10 32 04

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: mac
- Node: chrome
- npm: -
```

### PR DESCRIPTION
**Pull request by pandeymangg**
## What does this PR do?

Increases the revalidation time for the ee license check from 24 to 72 hours, and returns false instead of throwing an error if nothing goes right.

Fixes #2609 (issue)

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

File: packages/ee/lib/service.ts [hunk 1]
```diff
@@ -50,14 +53,14 @@ export const getIsEnterpriseEdition = async (): Promise<boolean> => {
   const hashedKey = hashString(ENTERPRISE_LICENSE_KEY);
```
Comment (mattinannt) [inline packages/ee/lib/service.ts:53]: Could we also move this `hashedKey` declaration to the top of the file and use them in all functions instead of passing it down as a prop since it stays the same on runtime?

**Review by mattinannt — CHANGES_REQUESTED** [review]
@pandeymangg thanks for the PR :-) Only one small suggestion / question to maybe avoid some unnecessary attributes

File: packages/ee/lib/service.ts (hunk 1 above)
Comment (pandeymangg) [reply packages/ee/lib/service.ts]: updated 🚀
