### PR TITLE
fix: formbricks version on localhost

### LINKED ISSUE #5205: Displaying current version of Formbricks is not working for self-hosters.
### Task description

Make it easy for self-hosters to see which version of Formbricks they are running

### PR DESCRIPTION
**Pull request by gupta-piyush19**
## What does this PR do?
formbricks version on localhost

Fixes #5205

## How should this be tested?

- self-hosting instance should have the correct version
- formbricks version should be hidden on localhost

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

## Summary by CodeRabbit

- **New Features**
  - Updated the navigation and settings pages so that version update notifications and version details now only appear in production environments, ensuring a cleaner interface during development.

### CODE REVIEW

File: packages/lib/constants.ts [hunk 1]
```diff
@@ -20,6 +20,7 @@ export const DEFAULT_BRAND_COLOR = "#64748b";
 export const FB_LOGO_URL =
   "https://s3.eu-central-1.amazonaws.com/listmonk-formbricks/Formbricks-Light-transparent.png";
 
+export const IS_LOCALHOST = ["localhost", "127.0.0.1", "::1"].includes(new URL(WEBAPP_URL).hostname);
```
Comment (pandeymangg) [inline packages/lib/constants.ts:23]: pls use the node_env "development" check here as its easier and then we won't need another constant at all 🙏

**Review by pandeymangg — CHANGES_REQUESTED** [review]
Thanks for the PR @gupta-piyush19 
pls just change the development check and then we're good to go 🚀

File: packages/lib/constants.ts (hunk 1 above)
Comment (mattinannt) [inline packages/lib/constants.ts]: Nodejs provides the `NODE_ENV` variable which is either `development` or `production`. I think this is the much better choice here, because it's also possible to run production Formbricks on localhost depending on the proxy setup.

**Review by mattinannt — CHANGES_REQUESTED** [review]

**Review by pandeymangg — APPROVED** [review]
