### PR TITLE
fix: default environment redirect

### LINKED ISSUE #6027: Organization member with `member` role does not reach the organization landing screen
### Issue Summary

In an organization, if you invite a member with the `member` role without assigning them to any team during the invitation process, the invited member does not land on the organization landing page. Instead, they encounter an error screen due to being redirected to the default (first) environment.

### Expected Behavior

The user should land on the organization landing screen after accepting the invite and logging in.

### Other information (incl. screenshots, Formbricks version, steps to reproduce,...)

Steps to reproduce:
1. Navigate to **Organization Settings > Access Control**.
2. Invite a new user with the `member` role, without assigning them to any team.
3. Accept the invitation and attempt to log in using the new member account.
4. The user is redirected to an error screen instead of the organization landing page.

### Your Environment

None

### PR DESCRIPTION
**Pull request by gupta-piyush19**
## What does this PR do?
Fixes the default environment redirect

Fixes #6027 

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

## Summary by CodeRabbit

- **New Features**
  - Project environment data is now personalized based on the current user, displaying only environments relevant to the user's memberships and roles.

- **Bug Fixes**
  - Updated data retrieval to ensure users only see project environments they have access to within selected organizations.

- **Tests**
  - Adjusted test cases to reflect the new user-specific project environment logic, including scenarios for membership absence and team-based access.

### CODE REVIEW

File: apps/web/lib/project/service.ts [hunk 1]
```diff
@@ -171,20 +171,58 @@ export const getOrganizationProjectsCount = reactCache(async (organizationId: st
...
         },
+      });
+
+      if (memberships.length === 0) {
+        return [];
+      }
+
+      const whereConditions: Prisma.ProjectWhereInput[] = [];
+
+      for (const membership of memberships) {
```
Comment (pandeymangg) [inline apps/web/lib/project/service.ts]: Can we replace this `for` with a map that goes like this:

```
      const whereConditions = memberships.map((membership) => {
        if (membership.role === "member") {
          return {
            organizationId: membership.organizationId,
            projectTeams: {
              some: {
                team: {
                  teamUsers: {
                    some: {
                      userId,
                    },
                  },
                },
              },
            },
          };
        }

        return {
          organizationId: membership.organizationId,
        };
      });
 ```
 
 would be better than to directly mutate a variable
