### PR TITLE
fix: Preview for short urls

### LINKED ISSUE #1819: [BUG][🕹️] Dynamic Link Preview broken incl. shortened links
### Issue Summary

This issue has two elements:

1. The Dynamic Link Preview does not work anymore:

_// solved_

2. The Link Preview does not (and maybe never did) work for Shortened URLs.

In Formbricks, you can shorten URLs via the top right menu:

Screenshot 2023-12-21 at 14 43 34

The shortened links do not have a preview:

image

Please fix it :)

### Steps to Reproduce

1. Create a link survey
2. Share URL in any service which creates link previews
3. Shorten URL and try again

### Expected behavior

Same dynamic link preview for both

### Other information

_No response_

### Screenshots

_No response_

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

### PR DESCRIPTION
**Pull request by KapadiaNaitik**
## What does this PR do?

Fixes #1819 

## How should this be tested?

- Create a short url 
- Check if preview is working

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

File: apps/web/app/[shortUrlId]/page.tsx [hunk 1]
```diff
@@ -1,8 +1,79 @@
...
+        locale: "en_US",
+        type: "website",
+      },
+      twitter: {
+        card: "summary_large_image",
+        title: survey.name,
+        description: "Create your own survey like this with Formbricks' open source survey suite.",
+        images: [ogImgURL],
+      },
+    };
```
Comment (ShubhamPalriwala) [inline apps/web/app/[shortUrlId]/page.tsx:72]: This seems repeatative to what we have here https://github.com/formbricks/formbricks/blob/main/apps/web/app/s/%5BsurveyId%5D/page.tsx

Can you wrap this into an action so that we can remove the duplication and then call it at one place easily?

**Review by ShubhamPalriwala — COMMENTED** [review]
Hey @KapadiaNaitik, thanks a lot for your changes 💪🏼 They work well, just one small change to follow the DRY principle more closely then we should be gtg 🚀

**Review by jobenjada — APPROVED** [review]
well done and sorry for the delay!
