### PR TITLE
fix: handle internal server error toast behavior in create organization

### LINKED ISSUE #3302: [BUG] Internal Server Errors still shows success toast
### Issue Summary

Sometimes internal server errors occur and the next server will respond with a `serverError: "Something went wrong while executing the operation."` (but still status code 200). Because of status 200 the frontend will not recognize it as an error and will still show a success toast (although something went wrong).
Formbricks should check the responses for a serverError when accessing backend functions:

```
if (result?.serverError) {
    throw new Error("Something went wrong");
}
```

### Steps to Reproduce

1. Use eg #3301 to trigger an unsuccessful server only action
2. success toast will pop up although the operation actually failed

This happens in many places where the toast will pop up when there is no error during a server side action.

### Expected behavior

An error toast indicating the issue pops up (instead of falsely suggesting a successful operation)

### Other information

_No response_

### Screenshots

_No response_

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- all Browsers
```

### PR DESCRIPTION
**Pull request by dingdyan**
Title: fix: handle internal server error toast behavior #3302

Description:

What does this PR do?

This PR fixes the issue where internal server errors (which return status 200) incorrectly trigger a success toast. I've added a serverError check to ensure the user receives accurate feedback when operations fail.

Fixes #3302

How should this be tested?

1. Use a scenario that triggers an unsuccessful server-side action (e.g., as described in issue #3301).
2. Observe that an error toast appears instead of a false success message.

Checklist

• [x] Filled out the "How to test" section in this PR
• [x] Read How we Code at Formbricks (https://formbricks.com/docs/contributing/how-we-code)
• [x] Self-reviewed my own code

### CODE REVIEW

File: apps/web/modules/setup/organization/create/components/create-organization.tsx [hunk 1]
```diff
@@ -35,11 +35,16 @@ export const CreateOrganization = () => {
     try {
       setIsSubmitting(true);
       const createOrganizationResponse = await createOrganizationAction({ organizationName });
+      if (createOrganizationResponse?.serverError) {
+        console.error("Create organization failed", { serverError: createOrganizationResponse.serverError }); toast.error(t("common.something_went_wrong"));
```
Comment (Dhruwang) [inline apps/web/modules/setup/organization/create/components/create-organization.tsx]: Please use the `getFormattedErrorMessage` function here and show its output as a toast message.

**Review by Dhruwang — CHANGES_REQUESTED** [review]

**Review by Dhruwang — APPROVED** [review]
Thanks for the fix. Looks good 🚀
