### PR TITLE
fix: adds support for `default_team_id` env var

### LINKED ISSUE #4788: DEFAULT_ORGANIZATION_ID no longer working as expected
### Issue Summary

We've been using `DEFAULT_ORGANIZATION_ID` and `DEFAULT_ORGANIZATION_ROLE` to automatically assign new users to our organization on their first login, granting them `member` rights. However, after the introduction of product-based access controls, this no longer works as expected.

Instead of having viewer access to the surveys, users now receive the following error message upon sign-up: "Your account doesn’t have access to any products yet."

### Expected Behavior

New users should be automatically assigned to the specified organization and granted viewer access upon their first login. Maybe we could add a variable like `DEFAULT_TEAM_ID` to automatically add them also to a specific team granting them certain access rights.

### Other information (incl. screenshots, Formbricks version, steps to reproduce,...)

_No response_

### Your Environment

Self-hosted Formbricks

### PR DESCRIPTION
**Pull request by gupta-piyush19**
WIP: refactoring is remaining
## What does this PR do?
adds support for `default_team_id` env var

Fixes #4788 

## How should this be tested?

- set the `default_organization_id` and `default_team_id` env var.
- Create a new user and check the team membership of the user in the default team.

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

## Summary by CodeRabbit

- **New Features**
  - Added support for assigning new users to a default team during signup and SSO provisioning.
  - Introduced environment variables for SSO team assignment and invite skipping.

- **Improvements**
  - Simplified signup and SSO flows by shifting from organization-based to team-based user assignment.
  - Enhanced error handling, validation, and caching in team membership management.
  - Updated environment variable handling and build configuration to reflect new team-centric setup.

- **Bug Fixes**
  - Corrected cache invalidation logic for team and project membership updates.

- **Documentation**
  - Updated environment variable documentation and configuration examples for new team-based settings.

- **Tests**
  - Added and updated tests to cover new team membership logic and SSO provisioning scenarios.
  - Introduced mocks and refined test isolation for team and membership functionalities.

- **Localization**
  - Updated authentication button text from "Azure" to "Microsoft" across multiple languages.

### CODE REVIEW

**Comment by jobenjada** [comment]
@jonas-hoebenreich wanna have an opinion on this PR? :)

**Comment by jonas-hoebenreich** [comment]
Yes, this sounds like exactly what we need :)

File: apps/web/modules/auth/signup/actions.ts [hunk 1]
```diff
@@ -93,47 +93,47 @@ export const createUserAction = actionClient.schema(ZCreateUserAction).action(as
...
+        ...user.notificationSettings,
+        alert: { ...user.notificationSettings?.alert },
+        weeklySummary: { ...user.notificationSettings?.weeklySummary },
+        unsubscribedOrganizationIds: Array.from(
+          new Set([...(user.notificationSettings?.unsubscribedOrganizationIds || []), organizationId])
+        ),
+      },
+    });
+
+    await createDefaultTeamMembership(user.id);
```
Comment (pandeymangg) [inline apps/web/modules/auth/signup/actions.ts:134]: I think we should first check if a `DEFAULT_TEAM_ID` is set in the environment variables before calling this service instead of having the check inside the service 🙏

File: apps/web/modules/auth/signup/lib/team.ts [hunk 2]
```diff
@@ -63,3 +70,73 @@ export const createTeamMembership = async (invite: CreateMembershipInvite, userI
     throw error;
   }
 };
+
+const getDefaultTeam = reactCache(
```
Comment (pandeymangg) [inline apps/web/modules/auth/signup/lib/team.ts:74]: please make a generic service here `getTeam` that takes the `teamId` and `organizationId` and fetches the required data with cache 🙏

File: apps/web/modules/ee/sso/lib/sso-handlers.ts [hunk 3]
```diff
@@ -132,13 +137,24 @@ export const handleSSOCallback = async ({ user, account }: { user: TUser; accoun
...
-      const role = isNewOrganization ? "owner" : DEFAULT_ORGANIZATION_ROLE || "manager";
+      const role = isNewOrganization ? "owner" : DEFAULT_ORGANIZATION_ROLE || "owner";
       await createMembership(organization.id, userProfile.id, { role: role, accepted: true });
       await createAccount({
         ...account,
         userId: userProfile.id,
       });
 
+      if (DEFAULT_TEAM_ID) {
+        await createTeamMembership(
```
Comment (pandeymangg) [inline apps/web/modules/ee/sso/lib/sso-handlers.ts:148]: pls check if this should be a call to `createDefaultTeamMembership` and change it if it needs to be 🙏

**Review by pandeymangg — CHANGES_REQUESTED** [review]
looks good! @gupta-piyush19 
pls see the comments that I left 🙏

**Review by pandeymangg — CHANGES_REQUESTED** [review]
thanks for the PR @gupta-piyush19 looks good!
I just suggested some code changes, pls take a look 🙏

File: apps/web/modules/auth/signup/lib/team.ts [hunk 4]
```diff
@@ -56,10 +54,143 @@ export const createTeamMembership = async (invite: CreateMembershipInvite, userI
...
+        }
+      },
+      [`getTeam-${teamId}`],
+      {
+        tags: [teamCache.tag.byId(teamId)],
+      }
+    )()
+);
+
+export const createDefaultTeamMembership = async (userId: string) => {
```
[the remark this answers is not in the document]
Comment (gupta-piyush19) [reply apps/web/modules/auth/signup/lib/team.ts:156]: The createTeamMembership function uses an invite object to create team memberships, as the organization membership is already validated. This is why we need a separate service for the default team ID membership, where we can check the organization membership for the default team.

**Review by pandeymangg — APPROVED** [review]
thx for the PR! LGTM! 🚀
