### PR TITLE
fix: input validation in management v2 webhooks API

### LINKED ISSUE #6017: Improper input validation in management v2 webhooks apis
### Issue Summary

API - `POST /api/v2/management/webhooks` and `PUT /api/v2/management/webhooks/[webhookId]`

The webhooks POST and PUT apis both have incorrect zod schema in place which does not let the user create or update a webhook with the `surveyIds` field set to an empty array.

When a webhook is created using the UI and the option `All current and new surveys` is checked, the webhook created in the db has an empty array as the `surveyIds` value.

Image

Image

But when the webhook is created with the `POST /api/v2/management/webhooks` api having the `surveyIds` field as an empty array, the api returns an error response with the message `not all surveys are in the same environment`

Image

### Expected Behavior

The api should create/update a webhook even though the `surveyIds` field is passed as an empty array.

### Other information (incl. screenshots, Formbricks version, steps to reproduce,...)

Steps to reproduce:
1. Try creating a webhook via the management v2 api `POST /api/v2/management/webhooks` with the following example JSON payload:
```js
{
    "name": "something new",
    "url": "https://discord.com",
    "source": "user",
    "environmentId": "<your-environment-id>",
    "triggers": [],
    "surveyIds": []
}
```
2. Observe the api response, its an error with the message `not all surveys are in the same environment`

### Your Environment

None

### PR DESCRIPTION
**Pull request by gupta-piyush19**
## What does this PR do?
fixes input validation in management v2 webhooks API

Fixes #6017 and #6010

## How should this be tested?

- Test with an empty survey ID array while creating or updating a webhook
- Also, test creating a webhook without triggers, it should return an error

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

## Summary by CodeRabbit

- **Bug Fixes**  
  - Improved error handling and conditional checks when updating webhooks to prevent unnecessary environment ID lookups and related errors.  
- **New Features**  
  - The webhook trigger field now requires at least one trigger, ensuring more precise configuration and validation.

### CODE REVIEW

File: apps/web/modules/api/v2/management/webhooks/[webhookId]/route.ts [hunk 1]
```diff
@@ -75,11 +75,18 @@ export const PUT = async (request: NextRequest, props: { params: Promise<{ webho
...
-      // get surveys environment
-      const surveysEnvironmentId = await getEnvironmentIdFromSurveyIds(body.surveyIds);
+      const hasSurveyIds = body.surveyIds && body.surveyIds.length > 0;
+      let surveysEnvironmentId: string | null = null;
 
-      if (!surveysEnvironmentId.ok) {
-        return handleApiError(request, surveysEnvironmentId.error, auditLog);
+      if (hasSurveyIds) {
+        // get surveys environment
+        const surveysEnvironmentIdResult = await getEnvironmentIdFromSurveyIds(body.surveyIds);
```
Comment (pandeymangg) [inline apps/web/modules/api/v2/management/webhooks/[webhookId]/route.ts]: I think we can change the return type `getEnvironmentIdFromSurveysIds` and just return null if it recieves an empty array, then we won't have this if condition here and can directly use the return value of `null`

**Review by pandeymangg — APPROVED** [review]
🚀
