### PR TITLE
fix: removes new session action

### LINKED ISSUE #4676: Remove "New Session" Event
### Task description

# Motivation

As part of the current revamp of the React Native SDK, we have removed the "New Session" event due to the complexity of supporting this feature in the updated SDK approach. 

The "New Session" event is a relic from the first version of the JS SDK, where actions and responses were grouped into sessions. In the current SDK version, "sessions" are no longer defined, and the triggering of this event has become somewhat unclear and inconsistent. 

For these reasons, we have decided to remove this event from Formbricks.

---

# Tasks

## 1. Remove the event for all new environments

Ensure that for new environments, this action is no longer created by default. Users will need to create their first action manually to begin using Formbricks SDKs.

---

## 2. Remove the event for existing environments if possible

Develop a data migration script to check whether the "New Session" event is being used in any survey for existing environments. 

- **If the event is not used as a survey trigger:** Safely delete it.  
- **If the event is used as a survey trigger:** Retain the action but convert it into a no-code action with the following settings:  

    Image

This ensures the "New Session" event continues to trigger every time the JS SDK initializes, even if the event itself is no longer part of the system.

---

## 3. Deprecate automatic actions

The "New Session" event was the only `automatic` action in Formbricks. With its removal, we can now deprecate automatic actions entirely. 

- Remove the `automatic` ActionType from the Prisma schema.  
- Use the new data migration approach to convert any existing "automatic" actions to "noCode" actions, ensuring consistency.  
- Remove all application code checks related to the `automatic` action class and clean up the codebase thoroughly.

### PR DESCRIPTION
**Pull request by pandeymangg**
## What does this PR do?

Fixes #4676 

## How should this be tested?

- Run the data migration
- Create a new environment and the new session action should not be created

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

## Summary by CodeRabbit

- **New Features**
	- The survey editor now displays a restored follow-ups view, enhancing survey management.
	- Action icons are now rendered consistently using a centralized lookup, offering a cleaner visual experience.
- **Bug Fixes**
	- Empty states in action lists now show a clear "no actions found" message.
	- Form fields and buttons in the action settings have been streamlined for improved usability.
	- Action deletion has been updated for a more seamless interaction.
	- The logic for retrieving in-progress surveys has been clarified without altering functionality.
	- Timeout settings in tests have been enhanced for better execution reliability.

### CODE REVIEW

File: apps/web/app/(app)/(survey-editor)/environments/[environmentId]/surveys/[surveyId]/edit/components/SavedActionsTab.tsx
Comment (gupta-piyush19) [inline apps/web/app/(app)/(survey-editor)/environments/[environmentId]/surveys/[surveyId]/edit/components/SavedActionsTab.tsx:1]: image
please add an empty state here 🙏

File: packages/database/migration/20250211050118_removed_new_session_event/migration.ts [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+  type: "data",
+  id: "dnh52k9vepinuhwuur8fclqf",
+  name: "20250211050118_removed_new_session_event",
+  run: async ({ tx }) => {
+    // Find all "New Session" actions
+    const newSessionActionsResult = await tx.$queryRaw`
+      SELECT id, name 
+      FROM "ActionClass" 
+      WHERE name = 'New Session' AND type = 'automatic'
+    `;
```
Comment (gupta-piyush19) [inline packages/database/migration/20250211050118_removed_new_session_event/migration.ts:13]: Please also handle the case of copied automatic actions.

File: packages/database/migration/20250211050118_removed_new_session_event/migration.ts [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+
+    console.log("Updating the rest of the automatic actions to noCode type");
+
+    const updatedActionsResult = await tx.$executeRaw`
+      UPDATE "ActionClass"
+      SET type = 'noCode'
+      WHERE type = 'automatic'
+    `;
+
+    console.log(`Updated ${updatedActionsResult.toString()} automatic actions`);
```
Comment (gupta-piyush19) [inline packages/database/migration/20250211050118_removed_new_session_event/migration.ts:63]: As we discussed, we can remove this since we will have 0 automatic actions after the above operations.

File: packages/database/migration/20250211050118_removed_new_session_event/migration.ts [hunk 3]
```diff
@@ -0,0 +1,65 @@
...
+        `;
+        updatedActions++;
+      } else {
+        // Delete unused action
+        await tx.$executeRaw`
+          DELETE FROM "ActionClass"
+          WHERE id = ${action.id}
+        `;
+        deletedActions++;
+      }
```
Comment (gupta-piyush19) [inline packages/database/migration/20250211050118_removed_new_session_event/migration.ts:48]: Please use `promise.all` for the updation and deletion operations.

**Review by gupta-piyush19 — CHANGES_REQUESTED** [review]
Thanks for the fix, @pandeymangg 🙌 
PR looks good and works fine. I've just suggested a few fixes. Could you please take a look at them?

**Review by gupta-piyush19 — APPROVED** [review]
LGTM 🚀
