### PR TITLE
fix: #1357 button text color changed on nearwhite background color

### LINKED ISSUE #1357: [BUG][FormTribe 🔥][50 Points] Button text not visible on white background.
### Issue Summary

The "Next" button of Survery is not visible on white background.

### Steps to Reproduce

1. Make a new account on formbricks.
2. Fill out the details of first two sets.
3. When you get to third set of details, Set the primary color field to complete white.
4. You will see that the next button in survey below is completely invisible now.

### Expected behavior

The button should be at least partially visible.

### Other information

_No response_

### Screenshots

image

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows
- Node: v18.13.0
- npm: 8.19.3
```

### PR DESCRIPTION
**Pull request by krishanu7**
## What does this PR do?
On changing the background color to white or a color close to white, the text color will change from white to black.
Fixes #1357 

[video](https://www.loom.com/share/cb906f0f4052453daa7ffa53c8d415f3?sid=3d15d243-3eb3-409d-a960-5f2e3074d5f8)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by jobenjada** [comment]
Hey! This is quite an unorthodox solution. Please build a Tailwind only solution. We also have a logic which determines if the text is black or white, add your solution there please;

**Comment by mattinannt** [comment]
@krishanu7 thank you for the PR.

@neilchauhan2 Can you please review the PR and check on the approach. I'm not sure if we already have an approach for this in the surveys package that is responsible for displaying the survey in Link Survey and in-app survey that we can reuse for this.

File: apps/web/app/(app)/onboarding/components/Product.tsx [hunk 1]
```diff
@@ -73,7 +73,25 @@ const Product: React.FC<Product> = ({ done, isLoading, environmentId, product })
...
+      const red = parseInt(r, 16);
+      const green = parseInt(g, 16);
+      const blue = parseInt(b, 16);
+      const brightness = (0.299 * red + 0.587 * green + 0.114 * blue) / 255;
+      const threshold = 0.9;
+      return brightness > threshold;
+    } else {
+      return false;
+    }
+  }
```
Comment (neilchauhan2) [inline apps/web/app/(app)/onboarding/components/Product.tsx:94]: Hi @krishanu7, thanks a lot for your contribution 🎉 . We already have a helper method in the codebase called `isLight` at `apps/web/app/lib/utils.ts` location, which takes in a color and returns a `true` value if the color is a light color otherwise it returns false.

You can use the same method to check if the current selected color is light or dark, and then apply the relevant white or black text.
Could you please replace your logic and instead use the method we already have, I'll re-review it once you are done with the changes.

cc: @mattinannt

**Review by neilchauhan2 — DISMISSED** [review]

**Comment by neilchauhan2** [comment]
> @krishanu7 thank you for the PR.
> 
> @neilchauhan2 Can you please review the PR and check on the approach. I'm not sure if we already have an approach for this in the surveys package that is responsible for displaying the survey in Link Survey and in-app survey that we can reuse for this.

@mattinannt, I've Added my review comment

**Review by mattinannt — APPROVED** [review]
I changed the PR to use the existing `isLight()` method 😊
