### PR TITLE
fix: unformatted db message in client display api

### LINKED ISSUE #6019: Unformatted db errors in the client display API
### Issue Summary

API - `POST /api/v1/client/[environmentId]/displays` and `POST /api/v2/client/[environmentId]/displays`

When trying to create a display with the client apis, if a non-existent `surveyId` is passed in the JSON payload, the api returns a `500 Internal Server Error` with an error message that comes directly from the db layer and is unformatted. This happens with both v1 and v2 apis.

Image

### Expected Behavior

The error message should be properly formatted:- `The survey with the <survey-id> is not found`. For the db errors, the error message should be a generic error message without leaking any info.

### Other information (incl. screenshots, Formbricks version, steps to reproduce,...)

Steps to reproduce:
1. Make a POST request to `/api/v2/client/[environmentId]/displays` with the JSON payload as:
```js
{
    // some non-existent surveyId
    "surveyId": "cmc0d8v"
}
```

### Your Environment

None

### PR DESCRIPTION
**Pull request by Dhruwang**
## What does this PR do?

Fixes #6019 
Screenshot 2025-07-07 at 2 24 30 PM

## How should this be tested?

Test client display api

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [x] Updated the Formbricks Docs if changes were necessary

## Summary by CodeRabbit

* **Bug Fixes**
  * Added explicit validation to ensure the referenced survey exists before creating a display, improving error feedback.
  * Internal server errors now return a generic message to avoid exposing technical details.

* **Tests**
  * Expanded test coverage for display creation, including handling missing surveys and database errors.
  * Added comprehensive tests for contact handling and error scenarios during display creation.

### CODE REVIEW

File: apps/web/app/api/v2/client/[environmentId]/displays/lib/display.ts [hunk 1]
```diff
@@ -5,17 +5,29 @@ import {
...
 
+    const survey = await prisma.survey.findUnique({
+      where: {
+        id: surveyId,
+        environmentId,
+      },
+    });
+    if (!survey) {
+      throw new InvalidInputError(
+        `The survey with id ${surveyId} and environmentId ${environmentId} does not exist.`
```
Comment (mattinannt) [inline apps/web/app/api/v2/client/[environmentId]/displays/lib/display.ts]: This error message suggests that both the `surveyId` as well as the `environmentId` do not exist which is misleading.

A better message would be something like "Survey ${surveyId} does not exist in environment ${environmentId}."

File: apps/web/app/api/v2/client/[environmentId]/displays/lib/display.ts [hunk 2]
```diff
@@ -5,17 +5,29 @@ import {
...
     const contactExists = contactId ? await doesContactExist(contactId) : false;
 
+    const survey = await prisma.survey.findUnique({
+      where: {
+        id: surveyId,
+        environmentId,
+      },
+    });
+    if (!survey) {
+      throw new InvalidInputError(
```
Comment (mattinannt) [inline apps/web/app/api/v2/client/[environmentId]/displays/lib/display.ts]: The input is valid, but the ressource is not found, so we should throw a `ResourceNotFoundError`

File: apps/web/app/api/v1/client/[environmentId]/displays/lib/display.ts [hunk 3]
```diff
@@ -31,6 +31,18 @@ export const createDisplay = async (displayInput: TDisplayCreateInput): Promise<
...
     }
 
+    const survey = await prisma.survey.findUnique({
+      where: {
+        id: surveyId,
+        environmentId,
+      },
+    });
+    if (!survey) {
+      throw new InvalidInputError(
```
Comment (mattinannt) [inline apps/web/app/api/v1/client/[environmentId]/displays/lib/display.ts]: same comments for the v2 api apply here :-)

File: apps/web/app/api/v2/client/[environmentId]/displays/lib/display.ts (hunk 1 above)
Comment (Dhruwang) [reply apps/web/app/api/v2/client/[environmentId]/displays/lib/display.ts]: As we not change this to ResourceNotFoundError, we no longer need this. ResourceNotFoundError would just take resource name and id ✅
Screenshot 2025-07-25 at 11 44 17 AM

**Review by mattinannt — APPROVED** [review]
@Dhruwang Thank you for making the changes. Looks much cleaner now :-)
