### PR TITLE
fix: replace button with div in IdBadge to prevent hydration issues (backport)

### LINKED ISSUE #6600: Hydration errors on prod
### Issue Summary

Image

also on the summary page (viewed live in a customer chat)

### Expected Behavior

UI to render properly

### Other information (incl. screenshots, Formbricks version, steps to reproduce,...)

It's very likely related to the ID component with a button inside of a button

### Your Environment

None

### PR DESCRIPTION
**Pull request by Dhruwang**
## Backport for Release/4.0

This is a backport of the hydration issue fix from main to the `release/4.0` branch.

## Problem

The `IdBadge` component was causing hydration issues when used inside other button elements, specifically in the `MultipleChoiceSummary` component. This occurred because the `IdBadge` component internally used a `<button>` element, which when placed inside another `<button>` creates invalid HTML structure and leads to React hydration errors.

## Steps to Reproduce

1. Navigate to a survey summary page with multiple choice questions
2. Observe the `MultipleChoiceSummary` component where `IdBadge` is used inside a clickable button
3. Check browser console for hydration errors indicating nested button elements
4. Notice UI breakage or inconsistent behavior

## Solution

- **Changed `<button>` to `<div>`**: Replaced the button element with a div that has `role="button"` in `badge-content.tsx`
- **Maintained Accessibility**: Preserved all ARIA attributes and keyboard interactions
- **Updated Tests**: Modified test selectors to work with the new div structure
- **Added Comment**: Added NOSONAR comment to explain why button cannot be used

## Technical Details

The issue specifically occurred in:
```tsx
// MultipleChoiceSummary.tsx (line 93-112)
<button onClick={setFilter}>
  {/* ... */}
  {choiceId && <IdBadge id={choiceId} />} // This was nesting buttons!
</button>
```

## Related Documentation

- [React Hydration Errors](https://react.dev/reference/react-dom/client/hydrateRoot#hydration-errors)
- [MDN: Button Element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#accessibility_concerns) - "Do not place interactive content such as anchors or buttons inside a button element"
- [ARIA Button Role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role)

## Testing

- ✅ All existing tests pass
- ✅ Accessibility is maintained with proper ARIA attributes
- ✅ Visual styling remains unchanged
- ✅ Copy functionality works as expected

## Original PR

This backports the changes from PR #6601

Fixes #6600

### CODE REVIEW

File: apps/web/modules/ui/components/id-badge/components/badge-content.tsx [hunk 1]
```diff
@@ -59,8 +59,8 @@ export const BadgeContent: React.FC<BadgeContentProps> = ({
   };
 
   const content = (
-    <button
-      type="button"
+    //NOSONAR - Cannot use button here because of hydration issues
+    <div
```
Comment (victorvhs017) [inline apps/web/modules/ui/components/id-badge/components/badge-content.tsx]: 🔧 **Fix**: The `//NOSONAR` comment should be inline to work, but due to the prettier call on the pre-commit hook, it's moving to the line above.

We need to fix the prettier formatting so that it does not do this in this case.

Fixing it will fix the reliability sonnarqube error checks in the PR

**Review by victorvhs017 — APPROVED** [review]
