### PR TITLE
fix: data migration for styling fixes

### LINKED ISSUE #2625: [BUG] color change after upgrade
### Issue Summary

After upgrading to v2.0.1 the brand color changed for all surveys that have custom styling enabled. Instead of `64748b` the default brand color should be used when enabling custom styles.

### Steps to Reproduce

1. Create survey with e.g. progress bar disabled
2. Upgrade your instance to v2.0.1
3. The button color of the survey changed

### Expected behavior

After upgrading the design of the surveys does not change.
Use the default brand color for custom styles not `64748b`.

### Other information

_No response_

### Screenshots

_No response_

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- v2.0.1
```

### PR DESCRIPTION
**Pull request by pandeymangg**
## What does this PR do?
Fixes a bug in the data migration script which leads to ignoring the product overwrites for the products that have default styling

Fixes #2625 (issue)

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

File: packages/database/data-migrations/20240320090315_add_form_styling/data-migration-fix.ts [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+      where: {
+        productOverwrites: {
+          not: Prisma.JsonNull,
+        },
+      },
+    });
+
+    for (const survey of surveysWithProductOverwrites) {
+      if (survey.productOverwrites) {
+        const { brandColor, highlightBorderColor, ...rest } = survey.productOverwrites;
```
Comment (mattinannt) [inline packages/database/data-migrations/20240320090315_add_form_styling/data-migration-fix.ts:17]: would it make sense to add a check here if `brandColor` & `highlightColor` is defined and only then update the survey. Because otherwise if the data-migration runs multiple times the surveys will be updated again.

File: packages/database/data-migrations/20240320090315_add_form_styling/data-migration-fix.ts
Comment (mattinannt) [inline packages/database/data-migrations/20240320090315_add_form_styling/data-migration-fix.ts:1]: Please also add a few console.log to the data migration.
See the `data-migration:refactor-actions` as a good example :-)

**Review by mattinannt — CHANGES_REQUESTED** [review]
@pandeymangg thanks for the PR :-) Looks good in general; I only have small suggestions for improvements :-)

**Review by mattinannt — APPROVED** [review]
@pandeymangg thanks for making the changes; looks great!! 😊💪
