### PR TITLE
fix: Each child in a list should have a unique "key" prop

### LINKED ISSUE #3532: [🕹️] Fix: Each child in a list should have a unique "key" prop
### What side quest or challenge are you solving?

Fixes the Warning: Each child in a list should have a unique "key" prop in file `packages/ui/components/TemplateList/components/TemplateFilters.tsx` and  `packages/ui/components/TemplateList/index.tsx`.

### Points

150

### Description

Solved the Warning: Each child in a list should have a unique "key" prop in file `packages/ui/components/TemplateList/components/TemplateFilters.tsx` and  `packages/ui/components/TemplateList/index.tsx`.

### Provide proof that you've completed the task

Screenshot 2024-10-12 at 2 11 37 PM
Screenshot 2024-10-12 at 2 08 10 PM

### PR DESCRIPTION
**Pull request by EzyHow**
## What does this PR do?

It fixes the Warning: Each child in a list should have a unique "key" prop in file `packages/ui/components/TemplateList/components/TemplateFilters.tsx` and  `packages/ui/components/TemplateList/index.tsx`.

Fixes #3532
Screenshot 2024-10-12 at 2 11 37 PM
Screenshot 2024-10-12 at 2 08 10 PM

### How to test
No changes required for testing.

### Required

- [✔] Filled out the "How to test" section in this PR
- [✔] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [✔] Self-reviewed my own code
- [✔] Commented on my code in hard-to-understand bits
- [✔] Ran `pnpm build`
- [✔] Checked for warnings, there are none
- [✔] Removed all `console.logs`
- [✔] Merged the latest changes from main onto my branch with `git pull origin main`
- [✔] My changes don't cause any responsiveness issues
- [✔] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

## Summary by CodeRabbit

- **New Features**
	- Improved performance of the Template Filters and Template List components by adding unique identifiers for rendered elements.
- **Bug Fixes**
	- Addressed potential rendering issues in lists by ensuring each component has a unique key.

### CODE REVIEW

File: packages/ui/components/TemplateList/components/TemplateFilters.tsx [hunk 1]
```diff
@@ -29,9 +29,8 @@ export const TemplateFilters = ({
       {allFilters.map((filters, index) => {
         if (prefilledFilters[index] !== null) return;
         return (
-          <div className="mt-2 flex flex-wrap gap-1 last:border-r-0">
+          <div key={index} className="mt-2 flex flex-wrap gap-1 last:border-r-0">
```
Comment (mattinannt) [inline packages/ui/components/TemplateList/components/TemplateFilters.tsx:32]: Using an index as a key in React is generally considered bad practice because it can lead to performance issues and bugs, especially when the list changes dynamically (e.g., items are added, removed, or reordered). React relies on keys to efficiently update and re-render components, and using the index can cause incorrect behavior in these scenarios because the index does not uniquely identify the items.

Can we get some kind of other id from the filters?

**Review by mattinannt — CHANGES_REQUESTED** [review]
@EzyHow thanks a lot for the PR and the fix :-)💪🚀  I only have one change request for your code:

File: packages/ui/components/TemplateList/components/TemplateFilters.tsx (hunk 1 above)
Comment (EzyHow) [reply packages/ui/components/TemplateList/components/TemplateFilters.tsx]: Thanks for pointing out this. I have updated it to `key={"key-" + filters[0]?.value || index}`. Now this code will use `filters` array first element's value as key and in case, `filters` array is empty, it will use index as backup key.

Hope this is okay? If anything else is required, please let me know.

**Review by mattinannt — APPROVED** [review]

**Comment by EzyHow** [comment]
@mattinannt Thanks for approving this PR.

BTW, I was expecting 150 points for oss.gg for this PR.

Thanks!
