### PR TITLE
fix: closing survey on mobile falsely positions it

### LINKED ISSUE #2856: [BUG][🕹️] Closing survey on mobile falsely positions it
### Issue Summary

If you close an app or website survey with the X button, it gets redisplayed higher than before:

https://github.com/formbricks/formbricks/assets/72809645/2bd1b938-f390-4f83-b81f-00acd61f3d42

### Steps to Reproduce

1. Create a website survey
2. Preview mobile
3. Answer first question
4. Close survey via X

### Expected behavior

It should be positioned like before

### Other information

_No response_

### Screenshots

_No response_

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [ ] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

### PR DESCRIPTION
**Pull request by mdm317**
I wasn't assigned to it, but I found it interesting, so I worked on it. If this behavior is not acceptable, please let me know.

Fixes #2856 

## What does this PR do?
Close an app or website survey with the X button, it gets redisplayed higher than before

I found two reasons why this issue occurs.

**first**
> https://github.com/formbricks/formbricks/blob/5848dfb4f3c4264b2385002e28a5e9c81d97c646/packages/surveys/src/components/wrappers/StackedCardsContainer.tsx#L183

The value is strange when the close button is pressed and `questionIdxTemp > currentQuestionIdx` has a difference of 2 or more.
For example, there are two questions and the close button is pressed after completing the survey.
Then that value will become `0, 0, 2, 3` but that value should be `-1, 0, 1, 2`

> https://github.com/formbricks/formbricks/blob/5848dfb4f3c4264b2385002e28a5e9c81d97c646/packages/surveys/src/components/wrappers/StackedCardsContainer.tsx#L54-L76 
This code only works correctly when the value of `questionIdxTemp > currentQuestionIdx` is less than 1.

This comment is the same issue.
> https://github.com/formbricks/formbricks/issues/2856#issuecomment-2219672713

I fix this problem at d59aff79b3d6542c53d74d627d3cff567ad74ae7

**second**

This occurs when a focus event is triggered on an element that is not visible.
For example, When the question type is free text, the question component automatically triggers a focus event on the textarea when it is rendered.

> https://github.com/formbricks/formbricks/blob/5848dfb4f3c4264b2385002e28a5e9c81d97c646/packages/ui/PreviewSurvey/index.tsx#L198-L204

But when close button, question component is still not visible because of transtion
> https://github.com/formbricks/formbricks/blob/5848dfb4f3c4264b2385002e28a5e9c81d97c646/packages/surveys/src/components/wrappers/Modal.tsx#L78

So ui was broken

I considered rendering the component only after it is fully visible, but I didn't implement it due to flickering issues. see below code example
 ```
const handlePreviewModalClose = () => { 
   setIsModalOpen(false); 
   setTimeout(() => { 
      setIsModalOpen(true); 
   }, 1000);
   setTimeout(()=>{
      setQuestionId(survey.welcomeCard.enabled ? "start" : survey?.questions[0]?.id); 
  }, 1500)
 }; 
```

So, I removed the code that opens the modal and replaced it with a reset function.

https://github.com/user-attachments/assets/0645c4e6-0173-4680-8fc7-f54b729e3ff9

## How should this be tested?

- create two or more questions.
- complete survey
- click close button

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

File: packages/surveys/src/components/wrappers/StackedCardsContainer.tsx [hunk 1]
```diff
@@ -45,35 +45,9 @@ export const StackedCardsContainer = ({
...
-      setVisitedQuestions((prev) => {
-        if (prev.length > 0) {
-          const newStack = prev.slice(0, -1);
-          return newStack;
-        }
-        return prev;
-      });
-    }
-    // eslint-disable-next-line react-hooks/exhaustive-deps
-  }, [questionIdxTemp]);
```
Comment (gupta-piyush19) [inline packages/surveys/src/components/wrappers/StackedCardsContainer.tsx:76]: These changes were introduced to fix another bug(https://github.com/formbricks/formbricks/commit/a91c9db4e0c2092e31e767ac771b72acff7925a5). In the case of the logic jump, the destination question was not animating. Can you please try creating a solution without removing this code, or can you fix it while keeping the same behaviour?
The incorrect index thing is something we need to check.

File: packages/ui/PreviewSurvey/index.tsx [hunk 2]
```diff
@@ -203,6 +203,14 @@ export const PreviewSurvey = ({
...
   };
 
+  const handleMobilePreviewModalClose = () => {
+    setIsModalOpen(false);
+    setTimeout(() => {
+      setIsModalOpen(true);
+      resetQuestionProgress();
+    }, 1000);
+  };
+
```
Comment (gupta-piyush19) [inline packages/ui/PreviewSurvey/index.tsx:213]: This looks good, but why are we doing it differently from the desktop?

**Review by gupta-piyush19 — CHANGES_REQUESTED** [review]
Thanks, @mdm317, for the changes.
I have added a few comments, can you please check them?
Thanks again for investigating the cause 🙌

File: packages/surveys/src/components/wrappers/StackedCardsContainer.tsx (hunk 1 above)
Comment (mdm317) [reply packages/surveys/src/components/wrappers/StackedCardsContainer.tsx]: Thanks for review!
I missed destination question feature. I reverted this commit.
To address the first reason I mentioned, , I chose to replace the code below with the `resetQuestionProgress` code instead of modifying `StackedCardsContainer` code.
> https://github.com/formbricks/formbricks/blob/e9c5b00628ca4a39fb3f8c9fab76bb9244d8a33d/packages/ui/PreviewSurvey/index.tsx#L201

File: packages/ui/PreviewSurvey/index.tsx (hunk 2 above)
Comment (mdm317) [reply packages/ui/PreviewSurvey/index.tsx]: I made it the same as on the desktop.

**Comment by gupta-piyush19** [comment]
Thanks, @mdm317, for the changes. This looks good now.
Just one more concern upon closing the survey, it blinks before re-appearing.
https://github.com/user-attachments/assets/f59aea4f-ac8b-439b-89e7-52d3ff030ae8
@jobenjada what do you think?

**Comment by jobenjada** [comment]
hey! We have two more issues, which are unrelated but now is a good opportunity to fix them:

1. The overlay preview is faulty on placement change:
https://github.com/user-attachments/assets/6eedd346-b0bb-4aaa-a908-e5f5da6dcc5a

2. overlayVisible variable handling in file PreviewSurvey -> Modal.tsx is off:
If the Overwrite Toggle is off, the `bg-white/50` class still gets applied.
image

3. The preview BG in the mobile preview is shown incorrectly if the survey was Link with custom background and then gets changed to website / app:
https://github.com/user-attachments/assets/2d6c63a0-055a-476c-bab0-6c561c3b4a0f

@Dhruwang pls fix this :)

**Review by Dhruwang — APPROVED** [review]
