### PR TITLE
fix: improper zod validation in action classes management API

### LINKED ISSUE #5995: Improper Zod Validation in action classes management api
### Issue Summary

API - POST `/api/v1/management/action-classes` and PUT `/api/v1/management/action-classes/[actionClassId]`

The zod validation in the v1 management api to create a new action class is broken. This has a couple of issues:
1. `environmentId` should be a mandatory field to pass along with the other fields in the payload, when not passing the `environmentId`, the api returns a `401 unauthorized` response, even though the whole logic of checking the permissions can be skipped just by having the `environmentId` field in the zod input.
2. There are some zod union errors even if the payload is correct, for example, in the screenshot below, the payload should be enough to create a new code action class but it results in a zod error. The `description` field seems to be mandatory to create a new action class, which it shouldn't be since in the UI as well the `description` is not required to create a new action class. Furthermore, the zod error details are also not correct as can be seen in the screenshot

Image

### Expected Behavior

The zod validation should work fine and action classes should be created with the management api

### Other information (incl. screenshots, Formbricks version, steps to reproduce,...)

_No response_

### Your Environment

None

### PR DESCRIPTION
**Pull request by gupta-piyush19**
## What does this PR do?
improper zod validation in action classes management API

Fixes #5995 

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

## Summary by CodeRabbit

- **Bug Fixes**
  - Improved input validation and permission checks to ensure they occur only after data is validated, reducing the risk of errors from malformed input.

- **New Features**
  - Enhanced form validation for action classes, including stricter checks on environment IDs and clearer handling of optional descriptions.
  - Improved input handling by distinguishing between different action class types for more accurate validation and feedback.

- **Documentation**
  - Updated API reference example for creating action classes to reflect current request structure and remove obsolete fields.

### CODE REVIEW

File: packages/types/action-classes.ts [hunk 1]
```diff
@@ -91,8 +91,11 @@ const ZActionClassInputBase = z.object({
     .string({ message: "Name is required" })
     .trim()
     .min(1, { message: "Name must be at least 1 character long" }),
-  description: z.string().nullable(),
-  environmentId: z.string(),
+  description: z.string().nullable().optional(),
+  environmentId: z
```
Comment (Dhruwang) [inline packages/types/action-classes.ts]: We can simply use ZId here like we do at other places and it would do the same 
Screenshot 2025-06-26 at 10 27 28 AM

File: packages/types/action-classes.ts [hunk 2]
```diff
@@ -91,8 +91,11 @@ const ZActionClassInputBase = z.object({
     .string({ message: "Name is required" })
     .trim()
     .min(1, { message: "Name must be at least 1 character long" }),
-  description: z.string().nullable(),
-  environmentId: z.string(),
+  description: z.string().nullable().optional(),
```
Comment (Dhruwang) [inline packages/types/action-classes.ts]: use `.nullish()` which allows both null and undefined in one go
