### PR TITLE
fix: recall in email embed

### LINKED ISSUE #4915: Embed code for email with question that recalls hidden fields
### Discussed in https://github.com/formbricks/formbricks/discussions/4906

<div type='discussions-op-text'>

<sup>Originally posted by **ks2018ks** March 10, 2025</sup>
Hi, just getting started trying out Formbricks...

The option to [embed the survey as HTML in an email](https://formbricks.com/docs/xm-and-surveys/surveys/link-surveys/embed-surveys#1-gmail) (showing the first question) is obviously a great way to increase the likelihood of response.

How do I do that in a way that preserves [hidden fields](https://formbricks.com/docs/xm-and-surveys/surveys/general-features/hidden-fields#hidden-fields) that I have set-up to pre-populate / customise the questions?

For example, if I have a question like this:
image

... how do I get the embed code to make sure the email looks like this:

image

...and not like this:
image

</div>

### PR DESCRIPTION
**Pull request by Dhruwang**
## What does this PR do?

Fixes #4915 

## How should this be tested?

Test recall parsing in email embed preview

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [x] Updated the Formbricks Docs if changes were necessary

## Summary by CodeRabbit

- **New Features**
	- Introduced a new `QuestionHeader` component for improved display of survey question headers.
- **Refactor**
	- Updated email preview to display headlines and subheaders with enhanced dynamic text processing.
	- Streamlined the parsing of dynamic recall patterns for improved text formatting and reliable fallback handling.

### CODE REVIEW

File: apps/web/modules/email/components/preview-email-template.tsx [hunk 1]
```diff
@@ -54,29 +55,26 @@ export async function PreviewEmailTemplate({
   const urlWithPrefilling = `${surveyUrl}?preview=true&skipPrefilled=true&`;
   const defaultLanguageCode = "default";
   const firstQuestion = survey.questions[0];
-
+  const headline = parseRecallInfo(getLocalizedValue(firstQuestion.headline, defaultLanguageCode), {}, {});
```
Comment (pandeymangg) [inline apps/web/modules/email/components/preview-email-template.tsx:58]: do we need the empty objects here? I think since they are optional and we use the `Object.keys` function, they will get evaluated to an empty array which is fine in itself

File: packages/lib/utils/recall.ts [hunk 2]
```diff
@@ -215,62 +215,51 @@ export const parseRecallInfo = (
...
-
-  if (responseData && questionIds.length > 0) {
-    while (modifiedText.includes("recall:")) {
-      const recallInfo = extractRecallInfo(modifiedText);
-      if (!recallInfo) break; // Exit the loop if no recall info is found
-
-      const recallItemId = extractId(recallInfo);
-      if (!recallItemId) return modifiedText; // Return the text if no ID could be extracted
+    const fallback = extractFallbackValue(recallInfo).replaceAll("nbsp", " ");
+    let value;
```
Comment (pandeymangg) [inline packages/lib/utils/recall.ts:233]: this value variable is typed as `any`, please type this

**Review by pandeymangg — CHANGES_REQUESTED** [review]
thanks for the fix @Dhruwang looks good already and works well, I just had a couple of comments, pls take a look 🙏

**Review by pandeymangg — APPROVED** [review]
