### PR TITLE
fix: Name can updated without any characters/value

### LINKED ISSUE #1015: [BUG] Name can updated without any characters/value
### Issue Summary

On profile page we can update name without giving values !

### Steps to Reproduce

On profile section check for name and email field :
1.u will see default name 
1.1 remove everything and try to update name [empty name]
1.2 you will get notification of name successfully updated

### Expected behavior

Should throw error "Enter at least one character"!

### Other information

_No response_

### Screenshots

https://www.loom.com/share/18841db953ef45d49da11195a3f25e39?sid=0dd02f30-a774-4ae2-bff5-b47a36271e33

checkout this video !

### Environment

- [X] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

### PR DESCRIPTION
**Pull request by adityadeshlahre**
## What does this PR do?

**People cannot submit empty names to update in there profile !**

Fixes #1015 

**LOOM VIDEO**

https://www.loom.com/share/7597d39761094ec5b8468ac244ee2680?sid=1b85e0eb-1377-4f00-b702-1556b33caca3

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- pnpm build
- pnpm lint
- pnpm test

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

If any changes required let me know : )
Thanks ! :smile:

### CODE REVIEW

**Review by ShubhamPalriwala — CHANGES_REQUESTED** [review]
Hey @adityadeshlahre, thanks a lot for the quick turnaround time. Before diving into the code deeply, I saw that you introducing a new dependency. Can you do it without it please if possible? Let me know if I can help in any way 🙏🏼

**Comment by adityadeshlahre** [comment]
hey @ShubhamPalriwala i have tried to do it but it was not giving desired out !

**issue : at first try just after reloading page it wast disabling the updated but we need to click on that once !
after that in second or n number of tried it was working fine !**

so i have added some packages to do that i tryed another thing where i was giving red error just bellow that input field !
it was working fine without dependency but same above issue was there 

after that i found out @mattinannt msg "if the "Update" button would get disabled when the input has length 0."

then i made some changes to achive that !

if any changes need to do please tell me.

thankyou :smile:

**Comment by ShubhamPalriwala** [comment]
Hey @adityadeshlahre, so we already use the "react-hook-form" in the `apps/web`v directory ie our app where you are also trying to make a change so you can use it there.

What you should do is remove it from the turborepo ie the core project's package json and lock files is because its not a core dependency. And since we already have the dependency already in that repo, you can do the validation using it as well.

Let me know if things are clear or you want some more help. Glad to see you reaching out back instantly 🚀

File: apps/web/app/(app)/environments/[environmentId]/settings/profile/EditName.tsx [hunk 1]
```diff
@@ -1,43 +1,74 @@
...
           <Label htmlFor="email">Email</Label>
           <Input type="email" id="fullname" defaultValue={profile.email} disabled />
         </div>
-        <Button type="submit" variant="darkCTA" className="mt-4" loading={isSubmitting}>
+        <Button
+          type="submit"
+          variant="darkCTA"
+          className="mt-4"
+          loading={isSubmitting}
+          disabled={isButtonDisabled || !!errors.name}>
```
Comment (ShubhamPalriwala) [inline apps/web/app/(app)/environments/[environmentId]/settings/profile/EditName.tsx:71]: Do we need this `!!errors.name` check here as well?

**Review by ShubhamPalriwala — COMMENTED** [review]
Hey, thanks for the quick fix! I've left some comments. Please address them, thoroughly test and then we can get going! 🤞🏼

**Comment by adityadeshlahre** [comment]
> Hey, thanks for the quick fix! I've left some comments. Please address them, thoroughly test and then we can get going! 🤞🏼
hey @ShubhamPalriwala did changes on latest commit according to your "comments"!
please have a look .
Thank You

**Review by ShubhamPalriwala — CHANGES_REQUESTED** [review]
Hey, thanks for making the changes! I tested the functionality and faced the following bugs:
- By default, the updateName is disabled, i'd prefer it to be enabled as a better UX
- If a user clears their entire current name, they cannot add any value
- If a user wants to add more than 1 word ie with spaces, they cannot do that
- In the updateProfileAction, why do we need the `data.name`, since we already have a state variable based on which we do the checks, it'd be better to do it with that.

The space issue is because you are trimming the value in the set name, you can try doing the trim only when you pass it to the updateProfileAction.



Here's a Loom video that addresses the same:
https://www.loom.com/share/80fb5c14361a48248ee81a8c0417b8e9?sid=8063e68e-1c78-443f-9ccf-a282c1af3119

File: apps/web/app/(app)/environments/[environmentId]/settings/profile/EditName.tsx [hunk 2]
```diff
@@ -1,43 +1,66 @@
...
+  const handleNameChange = (e: React.ChangeEvent<HTMLInputElement>) => {
+    const newNameValue = e.target.value;
+    setNameValue(newNameValue);
+    setButtonDisabled(newNameValue === "");
+  };
+
+  const onSubmit: SubmitHandler<FormData> = async (data) => {
+    try {
+      if (nameValue === "") {
+        toast.error("Please enter at least one character.");
```
Comment (mattinannt) [inline apps/web/app/(app)/environments/[environmentId]/settings/profile/EditName.tsx:33]: execution doesn't stop here and `updateProfileAction` as well as the success toast will get triggered

File: apps/web/app/(app)/environments/[environmentId]/settings/profile/EditName.tsx [hunk 3]
```diff
@@ -1,43 +1,66 @@
...
+
+  const handleNameChange = (e: React.ChangeEvent<HTMLInputElement>) => {
+    const newNameValue = e.target.value;
+    setNameValue(newNameValue);
+    setButtonDisabled(newNameValue === "");
+  };
+
+  const onSubmit: SubmitHandler<FormData> = async (data) => {
+    try {
+      if (nameValue === "") {
```
Comment (mattinannt) [inline apps/web/app/(app)/environments/[environmentId]/settings/profile/EditName.tsx:32]: use `data.name` here

File: apps/web/app/(app)/environments/[environmentId]/settings/profile/EditName.tsx [hunk 4]
```diff
@@ -1,43 +1,66 @@
...
           <Label htmlFor="email">Email</Label>
           <Input type="email" id="fullname" defaultValue={profile.email} disabled />
         </div>
-        <Button type="submit" variant="darkCTA" className="mt-4" loading={isSubmitting}>
+        <Button
+          type="submit"
+          variant="darkCTA"
+          className="mt-4"
+          loading={isSubmitting}
+          disabled={isButtonDisabled}>
```
Comment (mattinannt) [inline apps/web/app/(app)/environments/[environmentId]/settings/profile/EditName.tsx:63]: You can watch the input of `name` using react hook form instead of a custom logic and disable based on the value:
https://react-hook-form.com/docs/useform/watch

**Review by mattinannt — CHANGES_REQUESTED** [review]

**Comment by mattinannt** [comment]
@adityadeshlahre thanks a lot for the PR :-) 
I left you some comments for things I would like to see addressed before we merge the PR into main

**Comment by adityadeshlahre** [comment]
Hey @mattinannt and @ShubhamPalriwala sorry for late PR !
I have made changes according to comments of both of you.
please check it
Thank You :smile:

**Review by ShubhamPalriwala — APPROVED** [review]
LGTM! Thanks @adityadeshlahre, I added a small check to avoid API calls when the name is the same as what the user already has. 🚀

**Comment by ShubhamPalriwala** [comment]
Over to you @mattinannt

**Comment by adityadeshlahre** [comment]
> LGTM! Thanks @adityadeshlahre, I added a small check to avoid API calls when the name is the same as what the user already has. 🚀

Thanks Man ! :smile:

**Review by mattinannt — APPROVED** [review]
@adityadeshlahre Thanks a lot for the changes :-) 💪 Ready to merge
