### PR TITLE
fix: Call-to-Action statistics do not work as expected

### LINKED ISSUE #2450: [BUG] Call-to-Action statistics do not work as expected
### Issue Summary

The following test survey contains a single Call-to-Action question:
image

- the survey was displayed 730 times
- the survey was ignored 501 times
- the survey was dismissed 164 times
- users clicked the button 65 times

Out of this I would expect the following numbers:
- Displays: 730
- Starts: 65
- Completions/Responses: 65
- CTR: 8.9%
- Drop Offs: 665
- maybe display the additional number "Dismissals: 164"

Personally, I find it a bit strange that users who close the survey on the first question are counted as "response". In addition, the time to complete does not work at all in this case. Unfortunately, the CTR doesn't really work for surveys with conditional logic either.
~~I would also like the option to mark the CTA question as required.~~
Additionally, I would like to take this opportunity to suggest switching to the term "Impression" instead of "Displays / Views". This is currently not yet used consistently and the term "Impression" is the most prevalent in the industry.

### Steps to Reproduce

1. run survey with CTA question
2. check response count and CTR

### Expected behavior

Clicks on the button are counted as responses to that question, the CTR is calculated as (clicks) / (number of impressions).

### Other information

_No response_

### Screenshots

_No response_

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- v1.6.1
```

### PR DESCRIPTION
**Pull request by gupta-piyush19**
## What does this PR do?
- fix ttc logic, previously any survey having only 1 ques was not storing ttc value

Fixes #2450 

## How should this be tested?

- Fill any survey that contains only 1 ques, then check the time to complete values on the summary page

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [x] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by jobenjada** [comment]
Looks good, pushed a few tweaks.

However, the math doesn't really shake out, have a look:

image

How can it have 3 impressions and 3 clicks + 1 skip (4 user actions). Also, it has one skip so the CTR cannot be 100%.

Here is all the data to compare:

image

Thanks!

**Review by jobenjada — CHANGES_REQUESTED** [review]
see comment

**Review by jobenjada — APPROVED** [review]
works as expected - good work! :)

File: packages/types/surveys.ts [hunk 1]
```diff
@@ -679,6 +679,9 @@ export type TSurveyQuestionSummaryNps = z.infer<typeof ZSurveyQuestionSummaryNps
 export const ZSurveyQuestionSummaryCta = z.object({
   type: z.literal("cta"),
   question: ZSurveyCTAQuestion,
+  impressions: z.number(),
```
Comment (mattinannt) [inline packages/types/surveys.ts:682]: since we normally suffix numbers with `Count`, I think this also makes sense here.
So I would suggest doing these renamings:
`impressions` -> `impressionCount`
`clicks` -> `clickCount`
`skips` -> `skipCount`

**Review by mattinannt — CHANGES_REQUESTED** [review]

**Review by mattinannt — APPROVED** [review]
