### PR TITLE
fix: Add scroll to the setting navbar 

### LINKED ISSUE #1190: [BUG][FormTribe 🔥][50 Points] The compliance navigation section in the settings navbar is not completely visible on small screens
### Issue Summary

The compliance navigation section in the settings navbar is not completely visible on the desktop screen size.
Screenshot 2023-10-15 161852

### Steps to Reproduce

1. Go to settings
2. try to scroll the sidebar
3. you will see some part of the COMPLIANCE section is hidden

### Expected behavior

The compliance navigation should be visible on the full screen
Screenshot 2023-10-15 163911

### Other information

_No response_

### Screenshots

_No response_

### Environment

- [ ] Formbricks Cloud (app.formbricks.com)
- [X] Self-hosted Formbricks

### Desktop (please complete the following information)

```markdown
- OS: Windows
- Node: 18.17.0
- npm: 9.6.7
```

### PR DESCRIPTION
**Pull request by NilanjanPramanik**
## What does this PR do?

This PR added scroll to the setting navbar

Fixes #1190 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Test A
- Test B

### Required

- [ ] Filled out the "How to test" section in this PR
- [ ] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [ ] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues
- [ ] First PR at Formbricks? [Please sign the CLA!](https://formbricks.com/clmyhzfrymr4ko00hycsg1tvx) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

File: apps/web/app/(app)/environments/[environmentId]/settings/components/SettingsNavbar.tsx [hunk 1]
```diff
@@ -192,7 +192,7 @@ export default function SettingsNavbar({
 
   return (
     <>
-      <div className="fixed hidden h-full bg-white py-2 pl-4 pr-10 md:block ">
+      <div className="fixed hidden h-full overflow-y-scroll bg-white py-2 pl-4 pr-10 md:block ">
```
Comment (neilchauhan2) [inline apps/web/app/(app)/environments/[environmentId]/settings/components/SettingsNavbar.tsx:195]: Hi thank you for your contribution 🎉 , tried testing this on a 13" Mac but still the issue isn't resolved. Even on 100% zoom level not able to view the `License` link in the Compliance section. Attaching both 100% and 90% views. Can you please fix this, will re-review it once you are done with the fix.

  
Screenshot 2023-10-23 at 5 59 00 PM


Screenshot 2023-10-23 at 5 58 46 PM


cc: @mattinannt

**Review by neilchauhan2 — CHANGES_REQUESTED** [review]

**Review by mattinannt — APPROVED** [review]
thank you :-) the scroll itself is solved; unfortunately the last item is still not visible on small screens. But we can tackle this in a next PR.

File: apps/web/app/(app)/environments/[environmentId]/settings/components/SettingsNavbar.tsx (hunk 1 above)
Comment (mattinannt) [reply apps/web/app/(app)/environments/[environmentId]/settings/components/SettingsNavbar.tsx]: @neilchauhan2 yes, you are right. Unfortunately the contributor hasn't answered and I would like to merge this issue to complete the hackathon. Can you please approve the PR? :-)

**Review by neilchauhan2 — APPROVED** [review]
