### PR TITLE
fix: alert message on invalid file in file upload question

### LINKED ISSUE #6430: File upload widget does not list the uploaded files
### Issue Summary

As you can see in the attached screenshot, the UI does not show which files (if any) have already been uploaded. The only way I found to confirm the drag-and-drop worked is to try uploading the file again and see if an error message shows up.

### Expected Behavior

_No response_

### Other information (incl. screenshots, Formbricks version, steps to reproduce,...)

Image

### Your Environment

None

### PR DESCRIPTION
**Pull request by pandeymangg**
## What does this PR do?

Adds an alert message when the user tries to upload a file which is not supported by Formbricks.

Fixes #6430

## How should this be tested?
Screenshot 2025-08-18 at 10 25 35 AM

- Try uploading a file type that is not supported, for example a `.eml` file, the alert message should appear

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

**Comment by gupta-piyush19** [comment]
@pandeymangg Could you also address the text/plain file issue, as discussed?

File: packages/types/common.ts [hunk 1]
```diff
@@ -25,13 +25,15 @@ export const ZAllowedFileExtension = z.enum([
...
   "webp",
   "pdf",
+  "eml",
   "doc",
   "docx",
   "xls",
   "xlsx",
   "ppt",
   "pptx",
   "plain",
```
Comment (gupta-piyush19) [inline packages/types/common.ts]: Please either remove `plain` or change it to txt in the allowed file check

File: packages/surveys/src/components/general/file-input.tsx [hunk 2]
```diff
@@ -182,11 +182,14 @@ export function FileInput({
 
     // filter out files that are not allowed
     const validFiles = fileArray.filter((file) => {
-      const fileExtension = file.type.substring(file.type.lastIndexOf("/") + 1) as TAllowedFileExtension;
+      const fileExtension = file.name.split(".").pop()?.toLowerCase() as TAllowedFileExtension;
+      if (!fileExtension || fileExtension === file.name.toLowerCase()) return false;
+
```
Comment (gupta-piyush19) [inline packages/surveys/src/components/general/file-input.tsx:187]: Could there be a case where `!fileExtension` becomes true? We could check if the `file.name.split(“.”)` array has more than one element.

**Review by gupta-piyush19 — CHANGES_REQUESTED** [review]
Thanks for the PR, @pandeymangg! 
The changes look good, but please address the comments.

**Review by gupta-piyush19 — DISMISSED** [review]
Thanks, LGTM 🚀

**Review by gupta-piyush19 — APPROVED** [review]
