### PR TITLE
fix: auth checks in storage management api

### LINKED ISSUE #5919: Storage: Unable to Upload Public File via Management API
### Issue Summary

When attempting to upload a file using the v1 Management API's storage endpoint, the request fails with an unauthenticated error:
x-api-key header not provided or invalid.

However, the same x-api-key header works correctly with other endpoints in the Management API, suggesting the issue is isolated to the storage upload flow.

### Expected Behavior

The storage endpoint should return a valid signed upload URL and required metadata, allowing the next API call (which sends the file as multipart form data) to proceed successfully.

### Other information (incl. screenshots, Formbricks version, steps to reproduce,...)

Image
Don't worry about api-key, i'm in local env 😂.

Formbricks Version: 3.13.1

### Your Environment

Self-hosted Formbricks

### PR DESCRIPTION
**Pull request by Dhruwang**
## What does this PR do?

Fixes #5919 

## How should this be tested?

Try to upload files using storage management endpoint with api key
initially we didn't had logic to handle upload via api key and hence it always threw not authenticated error

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Read [How we Code at Formbricks](<[https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md](https://formbricks.com/docs/contributing/how-we-code)>)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [x] First PR at Formbricks? [Please sign the CLA!](https://cla-assistant.io/formbricks/formbricks) Without it we wont be able to merge it 🙏

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [x] Updated the Formbricks Docs if changes were necessary

## Summary by CodeRabbit

- **Refactor**
	- Streamlined authentication and authorization logic for file upload endpoints, supporting both session-based and API key-based access.
	- Unified required field validation with standardized error responses.

- **New Features**
	- Added clearer error messages when required fields are missing during file uploads.

- **Tests**
	- Introduced comprehensive unit tests for required field validation and authorization checks to ensure robust error handling.

- **Chores**
	- Disabled pre-commit hooks by commenting out the entire pre-commit script.

### CODE REVIEW

File: apps/web/app/api/v1/management/storage/local/route.ts [hunk 1]
```diff
@@ -53,14 +54,23 @@ export const POST = async (req: NextRequest): Promise<Response> => {
...
-
-  const isUserAuthorized = await hasUserEnvironmentAccess(session.user.id, environmentId);
-
-  if (!isUserAuthorized) {
-    return responses.unauthorizedResponse();
+  if (!session) {
+    //check whether its using API key
+    const authentication = await authenticateRequest(req);
+    if (!authentication) return responses.notAuthenticatedResponse();
+    const isAuthorized = authentication.environmentPermissions.some(
```
Comment (pandeymangg) [inline apps/web/app/api/v1/management/storage/local/route.ts]: can we replace this check with the helper `hasPermission` like we do at other places? I think the helper function `hasPermission` is defined under the api-key directory but we can make this reusable and directly use that in both the api routes 🙏

**Review by pandeymangg — CHANGES_REQUESTED** [review]
thanks for the PR @Dhruwang looks good!
I just have one comment, pls have a look 🙏

**Review by pandeymangg — APPROVED** [review]
LGTM! 🚀

**Review by pandeymangg — APPROVED** [review]
