### PR TITLE
Enhancement: Team creation taking a long time and demo product creation

### LINKED ISSUE #569: [ENHANCEMENT] Creating new team takes 20 seconds + Refactor Team Creation + Demo Product for new sign ups
### Issue Summary

- Due to the new Demo Product creation, creating a new team takes 20s
- New sign ups do not have a Demo Product (but they should)
- Currently, we have several point where a new team is created. This can be refactored

The main issue is the for loop that runs a lot of prisma call that are all awaited.
Screenshot 2023-07-17 at 10 10 14
Please find a way to reduce the prisma calls as well as only block execution if necessary and await the rest before returning the response.

### Steps to Reproduce

1. Create a new Team loads very long
grafik

### Tasks

1. Optimize the Prisma calls to create the team + demo data (consult with GPT :). It's in `environments > [environmentId] > actions.ts`
2. Find a smooth, non-blocking way so that new sign ups also find a second "Demo Product" when signing up. Maybe sideload it while they click through the Onboarding?

### PR DESCRIPTION
**Pull request by pandeymangg**
## What does this PR do?

Fixes #569  (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Create team using the create team modal, it does not take much time now
- Sign up with a new account and a demo product with the demo data is created

## Checklist

- [ ] Added a screen recording or screenshots to this PR
- [x] Filled out the "How to test" section in this PR
- [x] Read the [contributing guide](https://github.com/formbricks/formbricks/blob/main/CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Commented on my code in hard-to-understand bits
- [x] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues
- [ ] Updated the Formbricks Docs if changes were necessary

### CODE REVIEW

File: apps/web/pages/api/v1/teams/[teamId]/add_demo_product/index.ts [hunk 1]
```diff
@@ -0,0 +1,365 @@
...
+                    description: "The internal ID of the person",
+                    type: "automatic",
+                  },
+                  {
+                    name: "email",
+                    description: "The email of the person",
+                    type: "automatic",
+                  },
+                ],
+              },
```
Comment (ShubhamPalriwala) [inline apps/web/pages/api/v1/teams/[teamId]/add_demo_product/index.ts:131]: and can we write this once and just call the variable in both the places instead of writing it twice?

**Review by ShubhamPalriwala — CHANGES_REQUESTED** [review]
Hey @pandeymangg, great work on the PR 🚀, just tested it out locally and all worked well! Just a couple of small suggestions from my end, let me know what you think about them!

File: apps/web/components/auth/SignupForm.tsx [hunk 2]
```diff
@@ -27,14 +28,17 @@ export const SignupForm = () => {
...
     try {
-      await createUser(
+      const user = await createUser(
         e.target.elements.name.value,
         e.target.elements.email.value,
         e.target.elements.password.value,
         inviteToken
       );
+      const teamId = user.memberships[0].teamId;
+      addDemoProduct(teamId);
```
Comment (mattinannt) [inline apps/web/components/auth/SignupForm.tsx:41]: I think it would be better if we move the demo data creation call into the `api/v1/users` route (createUser) to always create a demoProduct when a new user / team is created.

File: apps/web/components/team/CreateTeamModal.tsx [hunk 3]
```diff
@@ -25,6 +26,10 @@ export default function CreateTeamModal({ open, setOpen }: CreateTeamModalProps)
   const submitTeam = async (data) => {
     setLoading(true);
     const newTeam = await createTeam(data.name, (profile as any).id);
+
+    // Add demo product to the newly created team in the background
+    addDemoProduct(newTeam.id);
```
Comment (mattinannt) [inline apps/web/components/team/CreateTeamModal.tsx:31]: same here, I think the `addDemoProduct` should happen inside the `createTeam` function.

File: pnpm-lock.yaml
Comment (ShubhamPalriwala) [inline pnpm-lock.yaml:1]: Let's not downgrade the versions?

**Review by ShubhamPalriwala — COMMENTED** [review]
lessgooo! 🚀 just a v small nit 😉

File: apps/web/lib/teams/teams.ts [hunk 4]
```diff
@@ -15,3 +16,19 @@ export const useTeam = (environmentId: string) => {
     mutateTeam: mutate,
   };
 };
+
+export const addDemoProduct = async (teamId: string) => {
```
Comment (mattinannt) [inline apps/web/lib/teams/teams.ts:20]: @pandeymangg Is this function still being used somewhere?

Comment (pandeymangg) [reply apps/web/lib/teams/teams.ts:20]: not right now, forgot to remove it from the code, will do it ☺️

File: pnpm-lock.yaml
Comment (pandeymangg) [reply pnpm-lock.yaml:1]: fixed

**Review by mattinannt — APPROVED** [review]
@pandeymangg Code looks great and everything is working nicely 😊 Your changes make the team creation process much faster 😊 Great job 💪🎉

**Review by ShubhamPalriwala — APPROVED** [review]
lessgoooo
